config/routes.rb
Rails.application.routes.draw do
  mount Bootsy::Engine => '/bootsy', as: 'bootsy'

root to: 'posts#new'
resources :posts

end

app/models/post.rb
class Post < ActiveRecord::Base
  include Bootsy::Container
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @post = Post.all
  end

  def new 
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to posts_path
    else
      flash[:danger] = @post.errors.full_messages
      redirect_to root_path
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :body, :bootsy_image_gallery_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyGreatApp</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/index.html.erb
<% @post.each do |post| %>
  <%= link_to post.title, post_path(post) %>
<% end %>

app/views/posts/new.html.erb
<div class = "container">
  <div id = "new-post">
    <%= form_for @post do |f| %>
    <div class="row">
      <div class="form-group">
        <%= f.label 'What are you teaching about today?*', class: "col-xs-7"%>
        <%= f.text_field :title, class: "col-xs-6" %>
      </div>
    </div>

    <div class="row">
      <div class="form-group">
        <%= f.label " ", class: "col-xs-7" %><br>
        <%= f.bootsy_area :body, cols: "50", rows: "10", id: "field", class: "col-xs-6"%>
        <div id="charNum" class = "col-xs-12"></div>
      </div>
    </div>

    <div class="row">
      <div class="form-group">
        <%= f.submit 'Create Post', class: "btn btn-primary" %>
      </div>
    </div>
    <% end %>
  </div>
</div>